name: creativetodo
description: Uma todo list linda e criativa.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_colorpicker: ^0.3.2
  sqflite: ^1.2.2
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

fonts:
  - family: Work Sans
    fonts:
      - asset: assets/fonts/WorkSans-Black.ttf
      - asset: assets/fonts/WorkSans-Bold.ttf
      - asset: assets/fonts/WorkSans-ExtraBold.ttf
      - asset: assets/fonts/WorkSans-ExtraLight.ttf
      - asset: assets/fonts/WorkSans-Light.ttf
      - asset: assets/fonts/WorkSans-Medium.ttf
      - asset: assets/fonts/WorkSans-Regular.ttf
      - asset: assets/fonts/WorkSans-SemiBold.ttf
      - asset: assets/fonts/WorkSans-Thin.ttf
